### ISSUE TITLE
Нейминг

### ISSUE THREAD

**Issue by Red-Cat-Fat** [Rainboom7/UnityClicker#2]
https://github.com/Rainboom7/UnityClicker/blob/28707beb0e2bce2bf3c6f8849ebfb752bee0e9cd/Clicker/Assets/Scripts/AddCounterActionBehaviour.cs#L8
### Отступы
Только TAB. Пробелам смерть!
### Имена

- Переменные внутри функции - с маленькой буквы camelCase (int someVar = 0;)
- Поле класса private/internal - с подчеркивания, _camelCase (private int _someVar;)
- Поле класса protected/public - с большой буквы, CamelCase (public int SomeVar;)
- Имена файлов, классов и неймспейсов - с большой буквы, CamelCase (EditorUtils.GUIWindow)
- Для свойств и событий - аналогично полям.
- Имя события не должно содержать On, должно заканчиваться на Event (public event System.Action ItemClickEvent;)
- Имя метода, отлавливающего событие должно содержать On, иметь совершённую форму и не должно заканчиваться на Event (private void OnItemClicked())
- Все имена функций - с большой буквы, CamelCase (private void SomeFunc())

### Общее

- Все поля, функции, свойства и события должны быть с явным модификатором (private/public/protected/internal)
- Для всех классов должен быть указан неймспейс
- Неймспейс определяется путем к скрипту, например скрипт в Assets/Scripts/Game/UI должен иметь неймспейс Game.UI, а скрипт в Assets/Scripts/Common/UI - неймспейс Common.UI
- Нельзя создавать неймспейс с именем используемых класса (Editor.Utils)
- {} скобки - на новой строке
- Не стоит пренебрегать {} для однострочных циклов и условий - меньше багов будет и проще потом править
- Unity создает по дефолту файлы с функциями Start и Update - обязательно удаляйте их если не используете

**Comment by Rainboom7** [comment]
https://github.com/Rainboom7/UnityClicker/commit/41468bd6e19501ae45f7e4f643f9660212e77ffe
