### ISSUE TITLE
OnEnable

### ISSUE THREAD

**Issue by Red-Cat-Fat** [Rainboom7/UnityClicker#3]
OnEnable срабатывает сам, когда объект активируется в сцене
https://github.com/Rainboom7/UnityClicker/blob/28707beb0e2bce2bf3c6f8849ebfb752bee0e9cd/Clicker/Assets/Scripts/CounterUpdateView.cs#L13

**Comment by Rainboom7** [comment]
https://github.com/Rainboom7/UnityClicker/commit/bd5b075f4853ff29acaa4abae5bb94b1b0eb0055
